# TCL File Generated by Component Editor 13.0
# Mon Apr 30 18:57:00 CST 2018
# DO NOT MODIFY


# 
# source_component "source_component" v1.0
# mmh 2018.04.30.18:57:00
# source_component
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module source_component
# 
set_module_property DESCRIPTION source_component
set_module_property NAME source_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP System
set_module_property AUTHOR mmh
set_module_property DISPLAY_NAME source_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL source_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file source_component.v VERILOG PATH hdl/source_component.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DMA_IDLE INTEGER 0
set_parameter_property DMA_IDLE DEFAULT_VALUE 0
set_parameter_property DMA_IDLE DISPLAY_NAME DMA_IDLE
set_parameter_property DMA_IDLE TYPE INTEGER
set_parameter_property DMA_IDLE UNITS None
set_parameter_property DMA_IDLE HDL_PARAMETER true
add_parameter READ INTEGER 1
set_parameter_property READ DEFAULT_VALUE 1
set_parameter_property READ DISPLAY_NAME READ
set_parameter_property READ TYPE INTEGER
set_parameter_property READ UNITS None
set_parameter_property READ HDL_PARAMETER true
add_parameter WAIT_READ INTEGER 2
set_parameter_property WAIT_READ DEFAULT_VALUE 2
set_parameter_property WAIT_READ DISPLAY_NAME WAIT_READ
set_parameter_property WAIT_READ TYPE INTEGER
set_parameter_property WAIT_READ UNITS None
set_parameter_property WAIT_READ HDL_PARAMETER true
add_parameter WRITE INTEGER 3
set_parameter_property WRITE DEFAULT_VALUE 3
set_parameter_property WRITE DISPLAY_NAME WRITE
set_parameter_property WRITE TYPE INTEGER
set_parameter_property WRITE UNITS None
set_parameter_property WRITE HDL_PARAMETER true
add_parameter WAIT_WRITE INTEGER 4
set_parameter_property WAIT_WRITE DEFAULT_VALUE 4
set_parameter_property WAIT_WRITE DISPLAY_NAME WAIT_WRITE
set_parameter_property WAIT_WRITE TYPE INTEGER
set_parameter_property WAIT_WRITE UNITS None
set_parameter_property WAIT_WRITE HDL_PARAMETER true
add_parameter CALC_NEXT INTEGER 5
set_parameter_property CALC_NEXT DEFAULT_VALUE 5
set_parameter_property CALC_NEXT DISPLAY_NAME CALC_NEXT
set_parameter_property CALC_NEXT TYPE INTEGER
set_parameter_property CALC_NEXT UNITS None
set_parameter_property CALC_NEXT HDL_PARAMETER true
add_parameter DMA_DONE INTEGER 6
set_parameter_property DMA_DONE DEFAULT_VALUE 6
set_parameter_property DMA_DONE DISPLAY_NAME DMA_DONE
set_parameter_property DMA_DONE TYPE INTEGER
set_parameter_property DMA_DONE UNITS None
set_parameter_property DMA_DONE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point read
# 
add_interface read avalon start
set_interface_property read addressUnits SYMBOLS
set_interface_property read associatedClock clock
set_interface_property read associatedReset reset
set_interface_property read bitsPerSymbol 8
set_interface_property read burstOnBurstBoundariesOnly false
set_interface_property read burstcountUnits WORDS
set_interface_property read doStreamReads false
set_interface_property read doStreamWrites false
set_interface_property read holdTime 0
set_interface_property read linewrapBursts false
set_interface_property read maximumPendingReadTransactions 0
set_interface_property read readLatency 0
set_interface_property read readWaitTime 1
set_interface_property read setupTime 0
set_interface_property read timingUnits Cycles
set_interface_property read writeWaitTime 0
set_interface_property read ENABLED true
set_interface_property read EXPORT_OF ""
set_interface_property read PORT_NAME_MAP ""
set_interface_property read SVD_ADDRESS_GROUP ""

add_interface_port read avm_read_address address Output 32
add_interface_port read avm_read_read read Output 1
add_interface_port read avm_read_readdata readdata Input 32
add_interface_port read avm_read_waitrequest waitrequest Input 1


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock
set_interface_property source associatedReset reset
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source aso_out0_data data Output 32
add_interface_port source aso_out0_ready ready Input 1
add_interface_port source aso_out0_valid valid Output 1

