# TCL File Generated by Component Editor 13.0
# Mon Apr 30 19:10:22 CST 2018
# DO NOT MODIFY


# 
# sink_component "sink_component" v1.0
# mmh 2018.04.30.19:10:22
# sink_component
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module sink_component
# 
set_module_property DESCRIPTION sink_component
set_module_property NAME sink_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP System
set_module_property AUTHOR mmh
set_module_property DISPLAY_NAME sink_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sink_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sink_component.v VERILOG PATH hdl/sink_component.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DMA_IDLE INTEGER 0
set_parameter_property DMA_IDLE DEFAULT_VALUE 0
set_parameter_property DMA_IDLE DISPLAY_NAME DMA_IDLE
set_parameter_property DMA_IDLE TYPE INTEGER
set_parameter_property DMA_IDLE UNITS None
set_parameter_property DMA_IDLE HDL_PARAMETER true
add_parameter READ INTEGER 1
set_parameter_property READ DEFAULT_VALUE 1
set_parameter_property READ DISPLAY_NAME READ
set_parameter_property READ TYPE INTEGER
set_parameter_property READ UNITS None
set_parameter_property READ HDL_PARAMETER true
add_parameter WAIT_READ INTEGER 2
set_parameter_property WAIT_READ DEFAULT_VALUE 2
set_parameter_property WAIT_READ DISPLAY_NAME WAIT_READ
set_parameter_property WAIT_READ TYPE INTEGER
set_parameter_property WAIT_READ UNITS None
set_parameter_property WAIT_READ HDL_PARAMETER true
add_parameter WRITE INTEGER 3
set_parameter_property WRITE DEFAULT_VALUE 3
set_parameter_property WRITE DISPLAY_NAME WRITE
set_parameter_property WRITE TYPE INTEGER
set_parameter_property WRITE UNITS None
set_parameter_property WRITE HDL_PARAMETER true
add_parameter WAIT_WRITE INTEGER 4
set_parameter_property WAIT_WRITE DEFAULT_VALUE 4
set_parameter_property WAIT_WRITE DISPLAY_NAME WAIT_WRITE
set_parameter_property WAIT_WRITE TYPE INTEGER
set_parameter_property WAIT_WRITE UNITS None
set_parameter_property WAIT_WRITE HDL_PARAMETER true
add_parameter CALC_NEXT INTEGER 5
set_parameter_property CALC_NEXT DEFAULT_VALUE 5
set_parameter_property CALC_NEXT DISPLAY_NAME CALC_NEXT
set_parameter_property CALC_NEXT TYPE INTEGER
set_parameter_property CALC_NEXT UNITS None
set_parameter_property CALC_NEXT HDL_PARAMETER true
add_parameter DMA_DONE INTEGER 6
set_parameter_property DMA_DONE DEFAULT_VALUE 6
set_parameter_property DMA_DONE DISPLAY_NAME DMA_DONE
set_parameter_property DMA_DONE TYPE INTEGER
set_parameter_property DMA_DONE UNITS None
set_parameter_property DMA_DONE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point write
# 
add_interface write avalon start
set_interface_property write addressUnits SYMBOLS
set_interface_property write associatedClock clock
set_interface_property write associatedReset reset
set_interface_property write bitsPerSymbol 8
set_interface_property write burstOnBurstBoundariesOnly false
set_interface_property write burstcountUnits WORDS
set_interface_property write doStreamReads false
set_interface_property write doStreamWrites false
set_interface_property write holdTime 0
set_interface_property write linewrapBursts false
set_interface_property write maximumPendingReadTransactions 0
set_interface_property write readLatency 0
set_interface_property write readWaitTime 1
set_interface_property write setupTime 0
set_interface_property write timingUnits Cycles
set_interface_property write writeWaitTime 0
set_interface_property write ENABLED true
set_interface_property write EXPORT_OF ""
set_interface_property write PORT_NAME_MAP ""
set_interface_property write SVD_ADDRESS_GROUP ""

add_interface_port write avm_write_address address Output 32
add_interface_port write avm_write_write write Output 1
add_interface_port write avm_write_writedata writedata Output 32
add_interface_port write avm_write_waitrequest waitrequest Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clock
set_interface_property sink associatedReset reset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink asi_in0_data data Input 32
add_interface_port sink asi_in0_ready ready Output 1
add_interface_port sink asi_in0_valid valid Input 1

